### ISSUE TITLE
Fixup tests before v3

### ISSUE THREAD

**Issue by jakobnissen** [BioJulia/BioSequences.jl#139]
Two things I'd like to improve on

* Some of my most recent changes here on version 2 have had insufficient testing. Ideally, I'd like to get coverage up near 100% again. This is much more easily achieved AFTER #138 , so this might be one of the later issues to address before v3
* There are way too many tests for BioSequences - nearly 9000 for LongSequence and 26000 for Mers. That's in package with 10k lines! On my (rather fast) laptop, they take 1.5 minutes. Not an eternity, but still a bit of wait. Worse, most of them don't really do anything except burn CI time and spam up the terminal if something goes wrong. I bet at least 75% of these tests could be eliminated if we cut down on test patterns, like
```
    for len in 1:64, _ in 1:10
        @test kmer_stuff(len, rand_seq(len))
    end
```
Do we really need 640 distinct tests here? What are the odds that function fails at k=54, and not before?

So, plan of action:
 - [x] Complete #138 , removing everything we don't want in this package
 - [x] Complete #121 , and any other new features to mers or longsequences
 - [x] Aggressively cut down on needless tests for mers and longsequences
 - [x] Add tests back to get near-100% coverage

Using [Aqua](https://github.com/JuliaTesting/Aqua.jl) on Julia exposes a few method ambiguities. In general, BioSequences have [an issue with method ambiguities](#135 ).

- [x] Fix method ambiguities (after all v3 feature issues, the possible interface rewrite, and #135 )

**Comment by kescobo** [comment]
This makes sense to me as well, and is the kind of thing that I and others can productively help with. Once you've got the cleanup done, I can take a stab at (3) and/or (4).

**Comment by jakobnissen** [comment]
Since broadcasting is going to be delayed to after the v3 release, and #203 is merged, this is done.
